---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/deployment.yml
- ../../base/service.yml
- route.yml

images:
- name: "play-java-grpc-example"
  newName: "docker-registry-default.centralpark.lightbend.com/play-java-grpc-example/play-java-grpc-example"
  newTag: "1.0-SNAPSHOT"